/**
* Enhanced content export utilities
*/

export const exportContent = (content, datasetName) => {
// Detect content type
const contentType = detectExportType(content);


// Generate filename
const timestamp = new Date().toISOString().slice(0, 10);
const sanitizedName = datasetName.toLowerCase().replace(/\s+/g, '-');
const filename = `${sanitizedName}-${contentType}-${timestamp}`;


// Export based on type
switch (contentType) {
case 'csv':
exportAsCSV(content, filename);
break;
case 'email':
exportAsEmail(content, filename);
break;
case 'markdown':
exportAsMarkdown(content, filename);
break;
default:
exportAsText(content, filename);
}
};

const detectExportType = (content) => {
if (content.includes('Subject:') && content.includes('Body:')) {
return 'email';
}
if (content.match(/^[^,\n]+,[^,\n]+/m)) {
return 'csv';
}
if (content.includes('##') || content.includes('###')) {
return 'markdown';
}
return 'text';
};

const downloadFile = (content, filename, mimeType) => {
const blob = new Blob([content], { type: mimeType });
const url = URL.createObjectURL(blob);
const link = document.createElement('a');
link.href = url;
link.download = filename;
document.body.appendChild(link);
link.click();
document.body.removeChild(link);
URL.revokeObjectURL(url);
};

const exportAsText = (content, filename) => {
downloadFile(content, `${filename}.txt`, 'text/plain');
};

const exportAsMarkdown = (content, filename) => {
downloadFile(content, `${filename}.md`, 'text/markdown');
};

const exportAsCSV = (content, filename) => {
downloadFile(content, `${filename}.csv`, 'text/csv');
};

const exportAsEmail = (content, filename) => {
// Format as .eml file
const emailContent = `${content}\n\n---\nGenerated by Kimi K2 Instructor`;
downloadFile(emailContent, `${filename}.txt`, 'text/plain');
};
